In [1]:
import numpy as np
a = np.random.randn(4,3)
print(a.shape)
b = np.random.randn(3,2)
print(b.shape)
#c = a*b
#print(c.shape)
d = np.random.randn(4,1)
print(d.shape)
e = a*d
print(e.shape)
print(a)
print(d)
print(e)

(4, 3)
(3, 2)
(4, 1)
(4, 3)
[[ 1.39059068  0.5194822   0.03050972]
 [ 0.30024158 -1.32948151  0.75980812]
 [-0.28822527 -0.54070349  0.83547999]
 [ 0.98005242 -0.17135858  0.67266266]]
[[-0.0538053 ]
 [ 0.59727819]
 [-0.64874727]
 [-1.53123267]]
[[-0.07482115 -0.0279509  -0.00164158]
 [ 0.17932775 -0.79407031  0.45381682]
 [ 0.18698536  0.35077991 -0.54201536]
 [-1.50068829  0.26238986 -1.03000304]]


In [2]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)
for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
print(c)
# c = a.T + b
# print(c)
# d = a + b.T
# print(d)

NameError: name 'c' is not defined